[package]
name = "glyphore-cli"
description = "MapLibre glyph PBF (SDF) generator — CLI"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "glyphore"
path = "src/main.rs"

[dependencies]
clap = { version = "4.6.0", features = ["derive"] }
glyphore-core = { path = "../glyphore-core" }
